# config
cover: /blog/uploads/cover.jpg
logo: /blog/uploads/avatar.jpg
bio: 'https://github.com/maywine'

# Content
excerpt_link: Read More

# Miscellaneous
#rss:

social: 
  github: https://github.com/maywine
